import { NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'

// POST: generate (or refresh) invite token for this company
export async function POST(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: lawyer } = await supabase.from('lawyers').select('id').eq('user_id', user.id).single()
  if (!lawyer) return Response.json({ error: 'Not found' }, { status: 404 })

  const { id } = await params

  const { data: membership } = await supabase
    .from('company_members')
    .select('role')
    .eq('company_id', id)
    .eq('lawyer_id', lawyer.id)
    .single()
  if (!membership || membership.role !== 'admin') {
    return Response.json({ error: 'Forbidden' }, { status: 403 })
  }

  // Delete any existing invites for this company
  await supabase.from('company_invites').delete().eq('company_id', id)

  // Create new invite (token generated by DB default)
  const expiresAt = new Date()
  expiresAt.setDate(expiresAt.getDate() + 7)

  const { data: invite, error } = await supabase
    .from('company_invites')
    .insert({
      company_id: id,
      created_by: lawyer.id,
      expires_at: expiresAt.toISOString(),
    })
    .select('token, expires_at')
    .single()

  if (error) return Response.json({ error: error.message }, { status: 500 })
  return Response.json({ token: invite.token, expires_at: invite.expires_at })
}

// GET: get current invite token
export async function GET(_req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: lawyer } = await supabase.from('lawyers').select('id').eq('user_id', user.id).single()
  if (!lawyer) return Response.json({ error: 'Not found' }, { status: 404 })

  const { id } = await params

  const { data: membership } = await supabase
    .from('company_members')
    .select('role')
    .eq('company_id', id)
    .eq('lawyer_id', lawyer.id)
    .single()
  if (!membership || membership.role !== 'admin') {
    return Response.json({ error: 'Forbidden' }, { status: 403 })
  }

  const { data: invite } = await supabase
    .from('company_invites')
    .select('token, expires_at')
    .eq('company_id', id)
    .gt('expires_at', new Date().toISOString())
    .single()

  return Response.json({ invite: invite ?? null })
}
